docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

version: 2
jobs:
  test-and-build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker-compose build
      - run:
          name: Test
          command: |
            docker-compose run test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-and-build-image
