version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path ./vendor/bundle
      - run:
          name: run tests
          command: bundle exec rspec
